### ISSUE TITLE
Add Aboriginal language group layer

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/mdba-hub#7]
Add Aboriginal language groups layer and apply as a filter for data views against MDBA datasets.

**Comment by ansell** [comment]
Can anyone point me at a shape file for this?

**Comment by ansell** [comment]
AIATSIS may want to commercialise the map that they hold for this purpose based on a data.gov.au administrator comment:

https://datagovau.ideascale.com/a/dtd/Shapefile-for-Aboriginal-Australia-Map/33804-26233

Hence, since there isn't a source immediately available for this at data.gov.au under an open license, just wondering whether anyone knows of any other sources that would be applicable to this layer and freely usable by ALA/MDBA.

**Comment by ansell** [comment]
Shapefile provided by MDBA, to be loaded ASAP:

https://data.gov.au/dataset/a-guide-to-traditional-owner-groups-for-water-resource-plan-areas

The actual shapefiles are in the attachment to that at:

https://data.gov.au/dataset/a-guide-to-traditional-owner-groups-for-water-resource-plan-areas/resource/c6290f37-afda-4a58-9527-d6ca10761e91

**Comment by ansell** [comment]
Surface water layer uploaded to spatial-test:

http://spatial-test.ala.org.au/spatial-service/manageLayers/layer/10847

Ground water layer uploaded to spatial-test:

http://spatial-test.ala.org.au/spatial-service/manageLayers/layer/10848

**Comment by ansell** [comment]
These have now been copied over to production.
